

services:
  mongodb:
    image: mongo:7
    container_name: mongo-medical
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
      - ./data:/import
    networks:
      - mongo_network

  migration:
    build: .
    container_name: mongo-migration
    depends_on:
      - mongodb
    networks:
      - mongo_network
    volumes:
      - ./data:/data
    command: >
      python src/migrate_cli.py
      --csv data/patients_sample.csv
      --export-json out.json
      --mongo-uri "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/?authSource=admin"
      --db ${MONGO_DB}
      --collection ${MONGO_COLLECTION}
      --id-field id

volumes:
  mongo_data:

networks:
  mongo_network:
    driver: bridge

